//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Badges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadgeStatu
    {
        public string UserId { get; set; }
        public int BadgeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public int StatusId { get; set; }
    
        public virtual Badge Badge { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
