//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string MarkerData { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string GeoData { get; set; }
        public string ImgUrl { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Parking Parking { get; set; }
    }
}
