//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OuMapDumpBuilding
    {
        public int Id { get; set; }
        public string loctitle { get; set; }
        public string loccode { get; set; }
        public string loctext { get; set; }
        public string lockeys { get; set; }
        public string locimg { get; set; }
        public string locid { get; set; }
        public string locurl { get; set; }
        public string locoptions { get; set; }
        public string geodata { get; set; }
        public string accessibility { get; set; }
        public string floorplan { get; set; }
        public string displayAs { get; set; }
    }
}
