//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public int fkGroupId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Contact { get; set; }
        public string ContactEmail { get; set; }
        public string Location { get; set; }
        public int EventIdFromSource { get; set; }
    
        public virtual CalendarGroup CalendarGroup { get; set; }
    }
}
